Repository apache/maven-surefire, pull requests merged in 2022-03, with the labels that each got.

#481 Add release-drafter to create gh releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: build

#480 Test only with 2 last Maven core 3.6.x and 3.8.x, avoid deep scanning to find jacoco files
  Jenkinsfile
Labels: build

#440 [SUREFIRE-1964] Support for method filtering on excludesFile and includesFile
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
  maven-surefire-plugin/src/main/java/org/apache/maven/plugin/surefire/SurefirePlugin.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/AbstractTestMultipleMethodPatterns.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1964IT.java
  surefire-its/src/test/resources/surefire-1964/exclusions.txt
  surefire-its/src/test/resources/surefire-1964/inclusions.txt
  surefire-its/src/test/resources/surefire-1964/pom.xml
  surefire-its/src/test/resources/surefire-1964/src/test/java/pkg/ExcludedTest.java
  surefire-its/src/test/resources/surefire-1964/src/test/java/pkg/FilterTest.java
Labels: enhancement

#485 [SUREFIRE-2036] Fix JUnit 5 with configured provider
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoTest.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2036IT.java
  surefire-its/src/test/resources/surefire-2036/pom.xml
  surefire-its/src/test/resources/surefire-2036/src/test/java/pkg/JUnit4Test.java
  surefire-its/src/test/resources/surefire-2036/src/test/java/pkg/JUnit5Test.java
Labels: bug
