Repository apache/maven-surefire, pull requests merged in 2022-12, with the labels that each got.

#585 [SUREFIRE-2136] Rename test dir that contains colon
  surefire-its/src/test/java/org/apache/maven/surefire/its/UmlautDirIT.java
Labels: maintenance

#581 Don't list minor bugs in specific outdated versions on the home page
  maven-surefire-plugin/src/site/apt/index.apt.vm
Labels: documentation

#564 [SUREFIRE-2032] Fix test count when using @Disabled at class level
  surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
  surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/RunListenerAdapterTest.java
Labels: bug

#576 [NO-JIRA] Refactor integration tests module
  surefire-its/src/test/java/org/apache/maven/surefire/its/AbstractTestMultipleMethodPatterns.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgCustomTestRunnerFactoryIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgJdk14IT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgReportTestIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgVersionsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/ClasspathFilteringIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/FailFastJUnitIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/FailFastTestNgIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/ForkCountIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47RedirectOutputIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47RerunFailingTestWithCucumberIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit4RerunFailingTestsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit4RunListenerIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitDepIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/Junit5ModulePathIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/LongWindowsPathIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/ModulePathIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/MultiModuleProjectWithJPMSIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/ReporterTime.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/ResultCountingIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/RunOrderIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/SmartStackTraceIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/Surefire1602IT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/TestMethodPatternIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/TestMultipleMethodsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/TestSingleMethodIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/TimeoutForkedTestIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/TwoTestCasesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/WorkingDirectoryIsInvalidPropertyIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/XmlReporterRunTimeIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/AbstractJava9PlusIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/TestFile.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1036NonFilterableJUnitRunnerWithCategoriesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1144XmlRunTimeIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1158RemoveInfoLinesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1202RerunAndSkipIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1265Java9IT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1534ReuseForksFalseWithJavaModuleIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1881IT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire257NotRerunningTestsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire570MultipleReportDirectoriesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire772BothReportsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire772NoFailsafeReportsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire817SystemExitIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire943ReportContentIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire975DefaultVMEncodingIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire979WrongClassLoaderIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire995CategoryInheritanceIT.java
Labels: maintenance, hacktoberfest-accepted

#549 [SUREFIRE-2101] - Fixes 'null' phrased test names with JUnit5 without @DisplayName
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/WrappedReportEntry.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/WrappedReportEntryTest.java
  surefire-api/src/main/java/org/apache/maven/surefire/api/report/CategorizedReportEntry.java
  surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReportEntry.java
  surefire-api/src/test/java/org/apache/maven/surefire/api/report/CategorizedReportEntryTest.java
Labels: bug

#587 [SUREFIRE-2101] JUnit5 console reporting: Fall back to class name
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetStats.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/TestSetStatsTest.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
Labels: bug
