Repository apache/maven-surefire, pull requests merged in 2022-04, with the labels that each got.

#507 [SUREFIRE-2044] Upgrade Maven Verifier to 1.8.0
  pom.xml
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/MavenLauncher.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire772NoFailsafeReportsIT.java
Labels: dependencies

#515 [SUREFIRE-2062] Remove code corresponding to jdk 7 from IT tests
  README.md
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNg740ParallelIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/CheckTestNgListenerReporterIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47RerunFailingTestWithCucumberIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnit47WithCucumberIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformEnginesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformRerunFailingTestsIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/JUnitPlatformStreamCorruptionIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/RunOrderIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireJUnit4IntegrationTestCase.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncher.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/SurefireLauncherTest.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/SpockIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1585IT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1914XmlReportingParameterizedTestIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire260TestWithIdenticalNamesIT.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire673MockitoIT.java
Labels: maintenance

#508 [SUREFIRE-2057] jpms requires static must be included
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/AbstractSurefireMojoJava7PlusTest.java
Labels: bug
