Repository apache/maven-surefire, pull requests merged in 2023-02, with the labels that each got.

#608 [SUREFIRE-2065] Fix parameterized JUnit4 test reporting
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/TestFile.java
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire2065IT.java
  surefire-its/src/test/resources/surefire-2065-common/pom.xml
  surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit4/ParameterizedTest.java
  surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit4/ParameterizedWithDisplayNameTest.java
  surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit5/ParameterizedTest.java
  surefire-its/src/test/resources/surefire-2065-common/src/test/java/pkg/junit5/ParameterizedWithDisplayNameTest.java
  surefire-its/src/test/resources/surefire-2065-junit4/pom.xml
  surefire-its/src/test/resources/surefire-2065-junit4/src/test/java/pkg/junit4/ParameterizedTest.java
  surefire-its/src/test/resources/surefire-2065-junit4/src/test/java/pkg/junit4/ParameterizedWithDisplayNameTest.java
  surefire-its/src/test/resources/surefire-2065-junit5/pom.xml
  surefire-its/src/test/resources/surefire-2065-junit5/src/test/java/pkg/junit5/ParameterizedTest.java
  surefire-its/src/test/resources/surefire-2065-junit5/src/test/java/pkg/junit5/ParameterizedWithDisplayNameTest.java
  surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/RunListenerAdapter.java
Labels: bug

#596 [SUREFIRE-2146] Don't draw border around reporting tables
  maven-surefire-report-plugin/src/main/java/org/apache/maven/plugins/surefire/report/SurefireReportGenerator.java
  maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/Surefire597Test.java
  surefire-api/src/test/java/org/apache/maven/surefire/api/testset/FundamentalFilterTest.java
Labels: enhancement

#570 [SUREFIRE-2119] - Sanitize failIfNoSpecifiedTests prefix in failsafe
  maven-failsafe-plugin/src/main/java/org/apache/maven/plugin/failsafe/IntegrationTestMojo.java
Labels: waiting-for-feedback
