Repository apache/maven-surefire, pull requests merged in 2025-03, with the labels that each got.

#815 [SUREFIRE-1643] surefire junit5 parallel tests
  Jenkinsfile
  maven-failsafe-plugin/pom.xml
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/CommonReflector.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/StartupReportConfiguration.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactory.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/StatelessXmlReporter.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/TestSetRunListener.java
  maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/report/WrappedReportEntry.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/CommonReflectorTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/MojoMocklessTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/ForkStarterTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/booterclient/TestSetMockReporterFactory.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/E2ETest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/extensions/EventConsumerThreadTest.java
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/report/DefaultReporterFactoryTest.java
  maven-surefire-plugin/pom.xml
  maven-surefire-report-plugin/pom.xml
  pom.xml
  surefire-api/src/main/java/org/apache/maven/surefire/api/booter/ForkingReporterFactory.java
  surefire-api/src/main/java/org/apache/maven/surefire/api/report/ReporterFactoryOptions.java
  surefire-api/src/test/java/org/apache/maven/surefire/api/util/internal/AsyncSocketTest.java
  surefire-booter/src/test/java/org/apache/maven/surefire/booter/SurefireReflectorTest.java
  surefire-its/pom.xml
  surefire-its/src/test/java/org/apache/maven/surefire/its/jiras/Surefire1643IT.java
  surefire-its/src/test/resources/surefire-1144-xml-runtime/src/test/java/surefire1144/Test1.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/.mvn/jvm.config
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/.mvn/maven.config
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/pom.xml
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/main/java/io/olamy/App.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/test/java/io/olamy/App1Test.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/test/java/io/olamy/App2Test.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/test/java/io/olamy/App3Test.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/test/java/io/olamy/App4Test.java
  surefire-its/src/test/resources/surefire-1643-parallel-junit5/src/test/java/io/olamy/App5Test.java
  surefire-providers/surefire-junit-platform/src/main/java/org/apache/maven/surefire/junitplatform/JUnitPlatformProvider.java
  surefire-providers/surefire-junit47/src/test/java/org/apache/maven/surefire/junitcore/JUnitCoreTester.java
Labels: bug

#817 Bump parent to 44
  pom.xml
  surefire-its/src/test/resources/surefire-1585-junit4-vintage/pom.xml
  surefire-providers/surefire-junit-platform/pom.xml
  surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/RunListenerAdapterTest.java
  surefire-providers/surefire-junit-platform/src/test/java/org/apache/maven/surefire/junitplatform/TestMethodFilterTest.java
Labels: dependencies

#819 Remove dependencies from root pom
  maven-failsafe-plugin/pom.xml
  maven-surefire-common/pom.xml
  maven-surefire-plugin/pom.xml
  maven-surefire-report-plugin/pom.xml
  pom.xml
  surefire-api/pom.xml
  surefire-booter/pom.xml
  surefire-extensions-api/pom.xml
  surefire-grouper/pom.xml
  surefire-its/pom.xml
  surefire-logger-api/pom.xml
  surefire-providers/common-java5/pom.xml
  surefire-providers/surefire-junit-platform/pom.xml
  surefire-providers/surefire-testng/pom.xml
  surefire-report-parser/pom.xml
Labels: maintenance

#822 Use newer version of surefire for itself testing, enable JUnit 5 in tests
  maven-failsafe-plugin/pom.xml
  maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/IntegrationTestMojoTest.java
  maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/JUnit4SuiteTest.java
  maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/MarshallerUnmarshallerTest.java
  maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/RunResultTest.java
  maven-failsafe-plugin/src/test/java/org/apache/maven/plugin/failsafe/VerifyMojoTest.java
  maven-surefire-common/pom.xml
  maven-surefire-common/src/test/java/org/apache/maven/plugin/surefire/SurefireDependencyResolverTest.java
  maven-surefire-common/src/test/java/org/apache/maven/surefire/JUnit4SuiteTest.java
  maven-surefire-plugin/pom.xml
  maven-surefire-report-plugin/pom.xml
  maven-surefire-report-plugin/src/test/java/org/apache/maven/plugins/surefire/report/JUnit4SuiteTest.java
  pom.xml
  surefire-api/pom.xml
  surefire-api/src/test/java/org/apache/maven/JUnit4SuiteTest.java
  surefire-api/src/test/java/org/apache/maven/surefire/api/util/SureFireFileManagerTest.java
  surefire-booter/pom.xml
  surefire-booter/src/test/java/org/apache/maven/surefire/booter/JUnit4SuiteTest.java
  surefire-extensions-api/pom.xml
  surefire-extensions-api/src/test/java/org/apache/maven/plugin/surefire/extensions/CommandlineExecutorTest.java
  surefire-extensions-api/src/test/java/org/apache/maven/plugin/surefire/extensions/JUnit4SuiteTest.java
  surefire-grouper/pom.xml
  surefire-its/pom.xml
  surefire-its/src/test/java/org/apache/maven/surefire/its/fixture/JUnit4SuiteTest.java
  surefire-logger-api/pom.xml
  surefire-logger-api/src/test/java/org/apache/maven/plugin/surefire/log/api/JUnit4SuiteTest.java
  surefire-providers/common-java5/pom.xml
  surefire-providers/common-junit3/pom.xml
  surefire-providers/common-junit4/pom.xml
  surefire-providers/common-junit48/pom.xml
  surefire-providers/pom.xml
  surefire-providers/surefire-junit3/pom.xml
  surefire-providers/surefire-junit4/pom.xml
  surefire-providers/surefire-junit47/pom.xml
  surefire-providers/surefire-testng-utils/pom.xml
  surefire-providers/surefire-testng/pom.xml
  surefire-report-parser/pom.xml
  surefire-report-parser/src/test/java/org/apache/maven/plugins/surefire/report/JUnit4SuiteTest.java
  surefire-shadefire/pom.xml
Labels: maintenance

#821 Update site descriptors
  maven-surefire-plugin/src/site/site.xml
  maven-surefire-report-plugin/src/site/site.xml
  src/site/site.xml
  surefire-api/src/site/site.xml
  surefire-providers/src/site/site.xml
Labels: maintenance

#825 surefire shared utils version current version
  pom.xml
Labels: maintenance

#826 assertj-core must be test scope
  surefire-providers/surefire-junit-platform/pom.xml
Labels: skip-changelog
